# Configuração PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_rh
spring.datasource.username=postgres
spring.datasource.password=202020
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true 

# Configuração Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false

# Configuração para upload de arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=temp

# Configuração adicional para resolver problemas de multipart
spring.http.multipart.enabled=true